### ISSUE TITLE
hi,sir do u think about this package to support HTML?

### ISSUE THREAD

**Issue by sunvim** [signintech/gopdf#15]
this package is very wonderfull, thank you for it.

my suggestion just like title.

I wish it can support this.

**Comment by oneplus1000** [comment]
I don't want to do that because I want this package do its job it should be, that is creating PDF. I think simple code that has one job and does that one job well is the way I like to get things done. If you want to creating PDF from HTML, you should create new package to read HTML and call gopdf for creating pdf. I think this is the way. Thank you for suggestion.

**Comment by the-world-wang** [comment]
i have two answers：
1. can i write something without setting the ttf font?
2. why  can't i write image after i write text

**Comment by oneplus1000** [comment]
Ans
1. You can draw line , draw oval.
2. This is example for write image after write text.

```GO
	package main

	import (
		"log"

		"github.com/signintech/gopdf"
	)

	func main() {
		pdf := gopdf.GoPdf{}
		pdf.Start(gopdf.Config{Unit: "pt", PageSize: gopdf.Rect{W: 595.28, H: 841.89}}) //595.28, 841.89 = A4
		pdf.AddPage()
		var err error
		err = pdf.AddTTFFont("loma", "../ttf/Loma.ttf")
		if err != nil {
			log.Print(err.Error())
			return
		}

		err = pdf.SetFont("loma", "", 14)
		if err != nil {
			log.Print(err.Error())
			return
		}
		pdf.Cell(nil, "hello")
		//#1 pic
		pdf.Image("../imgs/gopher.jpg", 200, 50, nil)

		pdf.SetX(250)
		pdf.SetY(200)
		pdf.Cell(nil, "gopher and gopher")

		pdf.WritePdf("image.pdf")
	}
