### ISSUE TITLE
pageNumber / TotalPages in each page

### ISSUE THREAD

**Issue by bbaulenas** [signintech/gopdf#292]
Hi! 
I'm struggling to put in each page a counter with actualPage/totalPages because I can't get total pages until I've added all of them.

So is there any way to setY to a specific page number? 

For now my solution is to render the same pdf 2 times, the first one to count the total pages and the second to render the same pdf with the page count.

I'm missing something?

Thank you.

**Comment by oneplus1000** [comment]
in this branch [placeholder](https://github.com/oneplus1000/gopdf/tree/placeholder)
I'm experimenting with adding a function to create a placeholder so that user can enter text later.
You can see an example from function TestPlaceHolderText,TestPlaceHolderText2 in this file [placeholder_test.go](https://github.com/oneplus1000/gopdf/blob/placeholder/placeholder_test.go).
Not sure if it will meet your needs or not.

**Comment by bbaulenas** [comment]
This is going to be really usefull.

Thank you!

**Comment by vantaboard** [comment]
> This is going to be really usefull.
> 
> Thank you!

@bbaulenas can you please close this issue if it has been resolved?
