### ISSUE TITLE
can't you upload a map of gb2312?

### ISSUE THREAD

**Issue by starchou** [signintech/gopdf#9]
I 'm from China, I want to use your product,But I can't use chinese. How can I get the gb2312.map or gbk.map?

**Comment by oneplus1000** [comment]
gopdf use map file from fpdf ( fpdf.org ). I don't know why fpdf not
provided gb2312.map ( or gbk.map )  ( by the way I am  Thai :-) ) . Next
release of gopdf will support 'no embed font'. I think it will solve your
problem, because gopdf can create pdf that use font in computer so
developers don't need to create font file.

**Comment by starchou** [comment]
I wish it support utf8...
what 's the time when gopdf release ?

**Comment by signintech** [comment]
gopdf has just updated with unicode subfont embedding.

**Comment by starchou** [comment]
3Q！great！
